Update timeout documentation
IBM/ibm-cloud-sdk-common pull request #43
Opened 2022-07-04 12:16 UTC by eiri

This PR adds a more accurate description for configured timeout in python and adds details on timeout defaults across the languages.

Closes:
- https://github.ibm.com/arf/planning-sdk-squad/issues/3164
- https://github.ibm.com/arf/planning-sdk-squad/issues/2836

2022-07-04 12:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/ibm-cloud-sdk-common?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/ibm-cloud-sdk-common?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/ibm-cloud-sdk-common?pullRequest=43) it.</sub>

2022-07-11 15:09 UTC, dpopp07 commented on README.md
> +By default the client has no request timeout, but a 30s connect timeout is set by default.
I think this working might be a little confusing. Are you trying to document that the underlying client package we use doesn't have a default but that the SDK core is setting a default? Is it important to clarify what the underlying client package's default behavior is? Perhaps I'm missing (or forgetting) some context as to the value of thatclarification

2022-07-11 16:13 UTC, padamstx commented on README.md
> +By default the client has no request timeout, but a 60s connect, a 90s read and a 60s write timeout are set by default.
```suggestion
By default, the client has a 60-second connect timeout, a 90-second read timeout and a 60-second write timeout.  The default client does not set a `call timeout` (which covers the entire HTTP call... including the connection, write and read steps), but you can set that as in the example above.
```

2022-07-11 17:02 UTC, eiri commented on README.md
> +# Configure a 10-second read timeout.
Yes, I know python's trying to be smart here and I've mulled over how to express it better for a while. In your wording it sounds like 10 seconds applied to both operations, so the total timeout will be 20 secs, while it's actually be half of that.

2022-07-11 17:10 UTC, eiri commented on README.md
> +The read timeout of 10 seconds, which includes the connect timeout, will be used in each operation invoked using `my_service`.
I don't think this is correct. `Requests` uses `urllib3` under the hood and quoting its docs
> (total) - This combines the connect and read timeouts into one; the read timeout will be set to the time leftover from the connect attempt. 

This described in the referenced issues and in [this ref ticket](https://github.ibm.com/arf/planning-sdk-squad/issues/2852)

2022-07-11 17:11 UTC, padamstx commented on README.md
> +# Configure a 10-second read timeout.
My reading of [this page](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts) is such that if you specify `timeout` as a single value, that value applies separately to connections and read operations.   So setting it to `10` means that a connection must be established before 10 secs elapses.  Then a separate/independent 10-second timeout is associated with the read operation.   I'm interpreting the docs this way due to the fact that a tuple (e.g. `timeout=(10, 20)`) can be used to specify the separate "connect" and "read" timeout values.  So it follows logically that `timeout=10` is equivalent to `timeout=(10, 10)` (i.e. connect timeout of 10s, followed by a read timeout of 10s).

2022-07-11 17:16 UTC, eiri commented on README.md
> +By default the client has no request timeout, but 60s read timeout, that includes the connect timeout is set by default.
Again, 60 secs is not as much applied to both connection and read operation as shared between them. Also they do not equal the request time, hence the original wording. Here is another quote from `urllib3`
> the read and total timeouts only measure the time between read operations on the socket connecting the client and the server, not the total amount of time for the request to return a complete response.

2022-07-11 17:49 UTC, padamstx commented on README.md
> +# Configure a 10-second read timeout.
Upon further review :)...  I re-read the "requests" documentation, plus I looked through some of the requests source code, along with some of the urllib3 documentation and source code, and it appears that the requests library simply passes through the timeout value to the urllib3 library.   I'll update my comments above...

2022-07-11 18:08 UTC, padamstx requested changes
I've removed some of my prior comments after more digging in "requests" and "urllib3".

2022-07-11 18:08 UTC, padamstx commented on README.md
> +The read timeout of 10 seconds, which includes the connect timeout, will be used in each operation invoked using `my_service`.
```suggestion
This timeout setting will be used in each operation invoked using `my_service`.
```

2022-07-11 19:32 UTC, padamstx approved these changes
I've re-reviewed and everything LGTM.

2022-07-11 19:33 UTC, merged